package com.ajaypatel.notify.it;

import com.ajaypatel.notify.support.AbstractIntegrationTest;
import com.ajaypatel.notify.support.ApiClient.TenantHandle;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static com.ajaypatel.notify.support.ApiClient.json;
import static org.assertj.core.api.Assertions.assertThat;

class IdempotencyIT extends AbstractIntegrationTest {

    private ResponseEntity<String> sendWithHeader(TenantHandle t, ObjectNode body, String key) {
        return api.call(HttpMethod.POST, "/api/v1/notifications", t.apiKey(), body, Map.of("Idempotency-Key", key));
    }

    @Test
    void repeatedKeyReturnsOriginalWith200() {
        TenantHandle t = api.newTenant();
        ObjectNode body = api.sendBody("SMS", "+911", null, "b");
        ResponseEntity<String> first = sendWithHeader(t, body, "k-1");
        assertThat(first.getStatusCode().value()).isEqualTo(202);
        ResponseEntity<String> second = sendWithHeader(t, body, "k-1");
        assertThat(second.getStatusCode().value()).isEqualTo(200);
        assertThat(json(second).get("id").asText()).isEqualTo(json(first).get("id").asText());
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM notifications WHERE tenant_id = ? AND idempotency_key = 'k-1'", Long.class, t.id());
        assertThat(count).isEqualTo(1);

        ResponseEntity<String> viaBody = api.post("/api/v1/notifications", t.apiKey(), api.sendBody("SMS", "+912", null, "b").put("idempotencyKey", "k-2"));
        assertThat(viaBody.getStatusCode().value()).isEqualTo(202);
        ResponseEntity<String> viaHeader = sendWithHeader(t, api.sendBody("SMS", "+912", null, "b"), "k-2");
        assertThat(viaHeader.getStatusCode().value()).isEqualTo(200);
        assertThat(json(viaHeader).get("id").asText()).isEqualTo(json(viaBody).get("id").asText());
    }

    @Test
    void concurrentSubmissionsWithSameKeyCreateExactlyOne() throws Exception {
        TenantHandle t = api.newTenant();
        ObjectNode body = api.sendBody("SMS", "+919", null, "race");
        int threads = 25;
        ExecutorService pool = Executors.newFixedThreadPool(threads);
        CountDownLatch start = new CountDownLatch(1);
        List<Future<ResponseEntity<String>>> futures = new ArrayList<>();
        try {
            for (int i = 0; i < threads; i++) {
                futures.add(pool.submit(() -> {
                    start.await();
                    return sendWithHeader(t, body, "race-1");
                }));
            }
            start.countDown();
            List<Integer> codes = new ArrayList<>();
            List<String> ids = new ArrayList<>();
            for (Future<ResponseEntity<String>> f : futures) {
                ResponseEntity<String> r = f.get(30, TimeUnit.SECONDS);
                codes.add(r.getStatusCode().value());
                ids.add(json(r).path("id").asText(null));
            }
            assertThat(codes).as("every racing request must succeed, got %s", codes).allMatch(c -> c == 202 || c == 200);
            assertThat(ids).allMatch(id -> id != null && id.equals(ids.get(0)));
            assertThat(Collections.frequency(codes, 202)).isEqualTo(1);
            assertThat(Collections.frequency(codes, 200)).isEqualTo(threads - 1);
            Long count = jdbc.queryForObject("SELECT COUNT(*) FROM notifications WHERE tenant_id = ? AND idempotency_key = 'race-1'", Long.class, t.id());
            assertThat(count).isEqualTo(1);
            api.awaitStatus(t, UUID.fromString(ids.get(0)), "SENT");
        } finally {
            pool.shutdownNow();
        }
    }

    @Test
    void idempotencyKeysAreScopedPerTenant() {
        TenantHandle a = api.newTenant();
        TenantHandle b = api.newTenant();
        ResponseEntity<String> ra = sendWithHeader(a, api.sendBody("SMS", "+911", null, "b"), "shared-key");
        ResponseEntity<String> rb = sendWithHeader(b, api.sendBody("SMS", "+911", null, "b"), "shared-key");
        assertThat(ra.getStatusCode().value()).isEqualTo(202);
        assertThat(rb.getStatusCode().value()).isEqualTo(202);
        assertThat(json(ra).get("id").asText()).isNotEqualTo(json(rb).get("id").asText());
    }

    @Test
    void keysWithoutHeaderOrBodyAreAutoGeneratedAndUnique() {
        TenantHandle t = api.newTenant();
        ObjectNode body = api.sendBody("SMS", "+911", null, "b");
        ResponseEntity<String> r1 = api.post("/api/v1/notifications", t.apiKey(), body);
        ResponseEntity<String> r2 = api.post("/api/v1/notifications", t.apiKey(), body);
        assertThat(json(r1).get("id").asText()).isNotEqualTo(json(r2).get("id").asText());
        assertThat(json(r1).get("idempotencyKey").asText()).startsWith("auto-");
        assertThat(json(r2).get("idempotencyKey").asText()).startsWith("auto-");
    }

    @Test
    void whitespaceIsTrimmed() {
        TenantHandle t = api.newTenant();
        ObjectNode body = api.sendBody("SMS", "+911", null, "b");
        ResponseEntity<String> first = sendWithHeader(t, body, " k-3 ");
        ResponseEntity<String> second = sendWithHeader(t, body, "k-3");
        assertThat(first.getStatusCode().value()).isEqualTo(202);
        assertThat(second.getStatusCode().value()).isEqualTo(200);
        assertThat(json(second).get("id").asText()).isEqualTo(json(first).get("id").asText());
    }
}
